uploads = []
outputs = []

[[generated]]
id = "Lx6t1s407xkBwojMTiXO0"
uri = "file://artifacts/mockup-sandbox/public/images/vv-hero.png"
type = "image"
title = "Auto repair shop hero"

[[generated]]
id = "5GKr0lu7mlBac56wqeP6k"
uri = "file://artifacts/mockup-sandbox/public/images/vv-brakes.png"
type = "image"
title = "Mechanic working on brakes"

[[generated]]
id = "idd9SPOfFPI6Ox29VYJ49"
uri = "file://artifacts/mockup-sandbox/public/images/vv-body.png"
type = "image"
title = "Auto body collision repair"

[[generated]]
id = "XhQo0qYj5BA0pAit0T5G3"
uri = "file://artifacts/vv-auto-website/public/images/vv-oil.png"
type = "image"
title = "Mechanic doing oil change"

[[generated]]
id = "CLDWukUqy7BB_MCRoMZEF"
uri = "file://artifacts/vv-auto-website/public/images/vv-engine.png"
type = "image"
title = "Mechanic doing engine repair"

[[generated]]
id = "DuXnAYC2SR02Ob5Si0-rO"
uri = "file://artifacts/vv-auto-website/public/images/vv-inspection.png"
type = "image"
title = "Mechanic doing state inspection"

[[generated]]
id = "gmP8PclpZy3tXcThQnlai"
uri = "file://artifacts/vv-auto-website/public/images/vv-diagnostics.png"
type = "image"
title = "Mechanic using computer diagnostic tool"

[[generated]]
id = "0RacVgHxaib1_vJMaDiiU"
uri = "file://artifacts/vv-auto-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"
